## 1 | Necessary Libraries

In [1]:
import numpy as np

In [2]:
from sklearn import preprocessing

In [3]:
from scipy import sparse

In [4]:
xTrain = np.array([[1, 2], [3, 4]])
xTrain

array([[1, 2],
       [3, 4]])

In [5]:
xTest = np.array([[1, 3], [4, 2]])
xTest

array([[1, 3],
       [4, 2]])

In [6]:
scaler = preprocessing.MinMaxScaler().fit(xTrain)
print(scaler.data_min_)
print(scaler.data_max_)

[1. 2.]
[3. 4.]


In [7]:
xTrain_Scaled = scaler.transform(xTrain)
xTrain_Scaled

array([[0., 0.],
       [1., 1.]])

In [8]:
xTest_Scaled = scaler.transform(xTest)
xTest_Scaled

array([[0. , 0.5],
       [1.5, 0. ]])

## 2 | Another - MaxAbsScaler

In [9]:
preprocessing.minmax_scale(xTrain)

array([[0., 0.],
       [1., 1.]])

In [10]:
xTrain = np.array([[-100, -200], [3, 4]])
xTrain

array([[-100, -200],
       [   3,    4]])

In [11]:
xTest = np.array([[-90, -150], [4, 3]])
xTest

array([[ -90, -150],
       [   4,    3]])

In [12]:
scaler = preprocessing.MaxAbsScaler().fit(xTrain)
print(scaler.max_abs_)

[100. 200.]


In [13]:
xTrain_Scaled = scaler.transform(xTrain)
xTrain_Scaled

array([[-1.  , -1.  ],
       [ 0.03,  0.02]])

In [14]:
xTest_Scaled = scaler.transform(xTest)
xTest_Scaled

array([[-0.9  , -0.75 ],
       [ 0.04 ,  0.015]])

In [15]:
preprocessing.maxabs_scale(xTrain)

array([[-1.  , -1.  ],
       [ 0.03,  0.02]])

## 3 | Matrix

In [16]:
xTrain = np.array([
    [1, 0, 0],
    [0, 5, 6],
    [7, 0, 0]
])
xTrain

array([[1, 0, 0],
       [0, 5, 6],
       [7, 0, 0]])

In [17]:
xTrain_CSR = sparse.csr_matrix(xTrain)
print(xTrain_CSR)

  (0, 0)	1
  (1, 1)	5
  (1, 2)	6
  (2, 0)	7


In [18]:
xTrain_CSC = sparse.csc_matrix(xTrain)
print(xTrain_CSC)

  (0, 0)	1
  (2, 0)	7
  (1, 1)	5
  (1, 2)	6


## 4 | MaxAbsScaler

In [19]:
scaler = preprocessing.MaxAbsScaler().fit(xTrain)
xTrain_Scaled = scaler.transform(xTrain)
print(xTrain_Scaled)

[[0.14285714 0.         0.        ]
 [0.         1.         1.        ]
 [1.         0.         0.        ]]


In [20]:
scaler_CSR = preprocessing.MaxAbsScaler().fit(xTrain_CSR)
xTrain_Scaled = scaler_CSR.transform(xTrain_CSR)
print(xTrain_Scaled)

  (0, 0)	0.14285714285714285
  (1, 1)	1.0
  (1, 2)	1.0
  (2, 0)	1.0


In [21]:
scaler_CSC = preprocessing.MaxAbsScaler().fit(xTrain_CSC)
xTrain_Scaled = scaler_CSC.transform(xTrain_CSC)
print(xTrain_Scaled)

  (0, 0)	0.14285714285714285
  (2, 0)	1.0
  (1, 1)	1.0
  (1, 2)	1.0


## 5 | StandardScaler [Compressed]

In [22]:
scaler = preprocessing.StandardScaler(with_mean=False).fit(xTrain)
xTrain_Scaled = scaler.transform(xTrain)
print(xTrain_Scaled)

[[0.32349832 0.         0.        ]
 [0.         2.12132034 2.12132034]
 [2.26448824 0.         0.        ]]


In [23]:
scaler = preprocessing.StandardScaler(with_mean=False).fit(xTrain_CSR)
xTrain_Scaled = scaler.transform(xTrain_CSR)
print(xTrain_Scaled)

  (0, 0)	0.3234983196103152
  (1, 1)	2.121320343559643
  (1, 2)	2.1213203435596424
  (2, 0)	2.2644882372722064


In [24]:
scaler = preprocessing.StandardScaler(with_mean=False).fit(xTrain_CSC)
xTrain_Scaled = scaler.transform(xTrain_CSC)
print(xTrain_Scaled)

  (0, 0)	0.3234983196103152
  (1, 1)	2.121320343559643
  (1, 2)	2.1213203435596424
  (2, 0)	2.2644882372722064


In [26]:
# END